# Permalinks
permalink:           pretty

# Setup
title:               Blog
tagline:             MyBlog
url:                 https://abitofbytes.com
baseurl:             /

# Owner/author information
owner:
  name:           Maikel Scheffer
  avatar:         avatar.png
  bio:            "Designer."

# Custom vars
version:             2.0.0
github:
  repo:              

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
